name: CI

on: 
  push:
    branches:
      - master
 
jobs:
  build:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@master
    - name: Go to directory
      run: cd theFork
    - name: Start xcodebuild test
      run: xcodebuild clean test -project theFork.xcodeproj -scheme theFork -destination "platform=iOS Simulator,name=iPhone 11 Pro"
